Repository kubernetes-sigs/krew, pull requests merged in 2019-09, with the labels that each got.

#322 lint: integrate impi
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#323 docs: Add link to GitHub template repo to developer guide
  docs/DEVELOPER_GUIDE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#327 lint: enable errcheck and fix some issues
  .golangci.yml
  cmd/krew/cmd/root.go
  cmd/validate-krew-manifest/main.go
  integration_test/testutil_test.go
  pkg/download/downloader.go
  pkg/download/verifier_test.go
  pkg/receiptsmigration/migration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#331 lint: integrate shfmt and reformat
  docs/CONTRIBUTOR_GUIDE.md
  hack/install-gox.sh
  hack/make-all.sh
  hack/make-binaries.sh
  hack/make-binary.sh
  hack/make-release-artifacts.sh
  hack/make-release-notes.sh
  hack/run-in-docker.sh
  hack/run-integration-tests.sh
  hack/run-lint.sh
  hack/run-tests.sh
  hack/verify-code-patterns.sh
  hack/verify-gofmt.sh
  hack/verify-installation.sh
  hack/verify-receipts-upgrade-migration.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#336 lint: bump golangci-lint to 1.18
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#334 Set up Travis CI for release binaries
  .travis.yml
  cmd/validate-krew-manifest/main.go
  docs/RELEASING_KREW.md
  hack/Dockerfile
  hack/cloudbuild-release.yaml
  hack/cloudbuild.yaml
  hack/krew.yaml
  hack/make-release-notes.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#333 Update README.md for krew v0.3.0
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#339 Remove krew.zip from release, add krew.exe
  .travis.yml
  README.md
  hack/krew.yaml
  hack/make-release-artifacts.sh
  hack/make-release-notes.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#341 Minor fixes for the release
  docs/RELEASING_KREW.md
  hack/krew.yaml
  hack/make-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#345 Fix handling when no matching platform is found
  pkg/installation/install.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#346 Upgrade to golangci-lint v0.19.0
  cmd/krew/cmd/list.go
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#347 Release v0.3.1
  README.md
Labels: approved, cncf-cla: yes, size/XS

#348 Update release instructions
  docs/RELEASING_KREW.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#349 Upgrade golangci-lint to v1.19.1
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
