Repository kubernetes-sigs/krew, pull requests merged in 2019-06, with the labels that each got.

#194 Fix IndexUrl to point to right url
  cmd/krew/cmd/update.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#202 Ensure index updates do not fail if the local and remote history diverge
  pkg/gitutil/git.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#197 cmd: info: Support only one argument
  cmd/krew/cmd/info.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#201 Add contributor documentation and helper scripts
  .dockerignore
  .travis.yml
  docs/CONTRIBUTOR_GUIDE.md
  hack/run-in-docker.sh
  hack/run-lint.sh
  hack/run-tests.sh
  hack/sandboxed.Dockerfile
  hack/verify-code-patterns.sh
  hack/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#207 Added link for contribution doc
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#203 Add basic integration tests
  .travis.yml
  cmd/krew/cmd/update.go
  cmd/krew/cmd/version.go
  docs/CONTRIBUTOR_GUIDE.md
  hack/run-integration-tests.sh
  hack/run-lint.sh
  hack/run-tests.sh
  pkg/constants/constants.go
  test/krew/index.go
  test/krew/krew.go
  test/krew_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#208 More integration tests
  docs/CONTRIBUTOR_GUIDE.md
  hack/run-integration-tests.sh
  test/krew_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#214 Make corneliusweig a maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, size/XS

#212 Remove obsolete `head` field from plugin manifest
  cmd/krew/cmd/info.go
  cmd/krew/cmd/install.go
  cmd/krew/cmd/upgrade.go
  cmd/validate-krew-manifest/main_test.go
  docs/DEVELOPER_GUIDE.md
  docs/KREW_ARCHITECTURE.md
  docs/PLUGIN_LIFECYCLE.md
  docs/USER_GUIDE.md
  pkg/index/indexscanner/testdata/testindex/dontscan.yaml
  pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
  pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
  pkg/index/types.go
  pkg/index/validate.go
  pkg/index/validate_test.go
  pkg/installation/install.go
  pkg/installation/upgrade.go
  pkg/installation/util.go
  pkg/installation/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#216 Add myself as krew maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#222 Put local imports in a separate import group
  .golangci.yml
  cmd/krew/cmd/list.go
  cmd/krew/cmd/root.go
  cmd/krew/cmd/search.go
  cmd/krew/cmd/uninstall.go
  cmd/krew/cmd/update.go
  cmd/krew/cmd/version.go
  cmd/krew/main.go
  cmd/validate-krew-manifest/main_test.go
  docs/CONTRIBUTOR_GUIDE.md
  hack/run-lint.sh
  hack/verify-gofmt.sh
  pkg/download/downloader_test.go
  pkg/environment/environment_test.go
  pkg/index/indexscanner/scanner.go
  pkg/index/indexscanner/scanner_test.go
  pkg/index/validate.go
  pkg/index/validate_test.go
  pkg/installation/install.go
  pkg/installation/util_test.go
  test/krew/index.go
  test/krew/krew.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#223 Small refactorings for better code structure
  cmd/krew/cmd/info.go
  cmd/krew/cmd/search.go
  cmd/validate-krew-manifest/main.go
  cmd/validate-krew-manifest/main_test.go
  hack/verify-code-patterns.sh
  pkg/constants/constants.go
  pkg/index/indexscanner/scanner.go
  pkg/index/platform.go
  pkg/index/platform_test.go
  pkg/installation/util.go
  pkg/installation/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#220 hack: move out install_kubectl_if_needed
  .travis.yml
  hack/ensure-kubectl-installed.sh
  hack/run-integration-tests.sh
Labels: approved, cncf-cla: yes, size/M

#218 Cleanup some TODOs
  cmd/krew/cmd/search.go
  cmd/validate-krew-manifest/main.go
  pkg/index/indexscanner/scanner.go
  pkg/index/indexscanner/scanner_test.go
  pkg/index/types.go
  pkg/index/validate.go
Labels: approved, cncf-cla: yes, size/M, ¯\_(ツ)_/¯

#215 Fix readme for wrong use of fish subshell in string
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#228 Various fixes to integration tests
  hack/ensure-kubectl-installed.sh
  hack/run-integration-tests.sh
  test/krew/krew.go
  test/krew_test.go
Labels: approved, cncf-cla: yes, size/L

#221 hack: update verify-code-patterns.sh
  hack/verify-code-patterns.sh
Labels: approved, cncf-cla: yes, size/XS

#230 Fix a broken link on README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
