Repository kubernetes-sigs/krew, pull requests merged in 2019-11, with the labels that each got.

#361 Improve error messages when installing from manifest+archive
  pkg/download/downloader.go
  pkg/download/fetch.go
  pkg/installation/install.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#363 Added condition for generating KUDO github stars
  cmd/generate-plugin-overview/generate-plugin-overview.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#368 Release v0.3.2
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#369 RELEASING_KREW: push only the release tag
  docs/RELEASING_KREW.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#326 Include list of merged pull requests in release notes
  hack/.gitignore
  hack/make-release-notes.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#370 Rely on standard utils for `IsSubPath`
  pkg/pathutil/pathutil.go
  pkg/pathutil/pathutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#372 Pin version of release-notes helper
  hack/make-release-notes.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#373 RELEASING_KREW: Specify the repository to push the tag to
  docs/RELEASING_KREW.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#376 Update golangci-lint to v1.21.0
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#380 Distribute LICENSE
  hack/krew.yaml
  hack/make-release-artifacts.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#367 Clean untracked files while updating index
  pkg/gitutil/git.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#381 Run go mod tidy
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#375 Use renameOrCopy for single-file move operation
  pkg/installation/install.go
  pkg/installation/move.go
  pkg/installation/move_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#377 Improve logic to determine if receipts migration is necessary
  integration_test/testutil_test.go
  pkg/receiptsmigration/migration.go
  pkg/receiptsmigration/migration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#385 Preserve installation error by wrapping
  cmd/krew/cmd/install.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#387 Refactor: move errorFetcher struct to test file
  pkg/download/downloader_test.go
  pkg/download/fetch.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#389 Drop GOPROXY since same with default
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#386 Make logging more consistent for downloaded vs. local archives
  pkg/download/downloader.go
  pkg/download/fetch.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#390 Migrate from glog to klog
  cmd/generate-plugin-overview/go.mod
  cmd/generate-plugin-overview/go.sum
  cmd/krew/cmd/install.go
  cmd/krew/cmd/root.go
  cmd/krew/cmd/uninstall.go
  cmd/krew/cmd/update.go
  cmd/krew/cmd/upgrade.go
  cmd/krew/main.go
  cmd/validate-krew-manifest/main.go
  go.mod
  go.sum
  hack/verify-code-patterns.sh
  pkg/download/downloader.go
  pkg/download/fetch.go
  pkg/download/verifier.go
  pkg/environment/environment.go
  pkg/gitutil/git.go
  pkg/index/indexscanner/scanner.go
  pkg/info/info.go
  pkg/installation/install.go
  pkg/installation/move.go
  pkg/installation/platform.go
  pkg/installation/upgrade.go
  pkg/installation/util.go
  pkg/receiptsmigration/migration.go
  pkg/receiptsmigration/oldenvironment/environment.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#394 [docs] Improve annotated plugin manifest
  docs/DEVELOPER_GUIDE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#395 Bump min go to v1.13 in go.mod
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#393 Fail validation when manifest has line break in `shortDescription`
  pkg/index/validation/validate.go
  pkg/index/validation/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#398 Fix version in readme fish installation
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#397 Drop GZIP env in artifact building
  hack/make-release-artifacts.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#396 Drop GO111MODULE env variable
  .travis.yml
  hack/install-gox.sh
  hack/make-binaries.sh
  hack/run-integration-tests.sh
  hack/run-lint.sh
  hack/run-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#407 Update OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#408 Update post installation text
  cmd/krew/cmd/info.go
  cmd/krew/cmd/install.go
Labels: approved, cncf-cla: yes, lgtm, size/S
