Repository kubernetes-sigs/krew, pull requests merged in 2019-05, with the labels that each got.

#178 Switch all repo references from `GoogleContainerTools` -> `kubernetes-sigs`
  .travis.yml
  cmd/krew/cmd/info.go
  cmd/krew/cmd/install.go
  cmd/krew/cmd/list.go
  cmd/krew/cmd/remove.go
  cmd/krew/cmd/root.go
  cmd/krew/cmd/search.go
  cmd/krew/cmd/update.go
  cmd/krew/cmd/upgrade.go
  cmd/krew/cmd/version.go
  cmd/krew/main.go
  cmd/validate-krew-manifest/main.go
  cmd/validate-krew-manifest/main_test.go
  docs/DEVELOPER_GUIDE.md
  docs/NAMING_GUIDE.md
  docs/RELEASING_KREW.md
  hack/Dockerfile.build
  hack/krew.yaml
  hack/make-binaries.sh
  hack/make-release-notes.sh
  pkg/environment/environment.go
  pkg/index/indexscanner/scanner.go
  pkg/installation/install.go
  pkg/installation/install_test.go
  pkg/installation/move.go
  pkg/installation/move_test.go
  pkg/installation/upgrade.go
  pkg/installation/util.go
  pkg/installation/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#177 Add some github shields
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 Switch imports to sigs.k8s.io/krew
  .travis.yml
  cmd/krew/cmd/info.go
  cmd/krew/cmd/install.go
  cmd/krew/cmd/list.go
  cmd/krew/cmd/remove.go
  cmd/krew/cmd/root.go
  cmd/krew/cmd/search.go
  cmd/krew/cmd/update.go
  cmd/krew/cmd/upgrade.go
  cmd/krew/cmd/version.go
  cmd/krew/main.go
  cmd/validate-krew-manifest/main.go
  cmd/validate-krew-manifest/main_test.go
  hack/Dockerfile.build
  hack/make-binaries.sh
  pkg/environment/environment.go
  pkg/index/indexscanner/scanner.go
  pkg/installation/install.go
  pkg/installation/install_test.go
  pkg/installation/move.go
  pkg/installation/move_test.go
  pkg/installation/upgrade.go
  pkg/installation/util.go
  pkg/installation/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#187 add: description how to install krew on fish
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#176 Switch linter from gometalinter to golangci-lint
  .travis.yml
  cmd/krew/cmd/search.go
  docs/DEVELOPER_GUIDE.md
  hack/cloudbuild-release.yaml
  hack/gometalinter.json
  hack/run_lint.sh
  pkg/download/downloader.go
  pkg/download/downloader_test.go
  pkg/download/fetch_test.go
  pkg/environment/environment.go
  pkg/installation/install.go
  pkg/installation/move.go
  pkg/installation/upgrade.go
  pkg/installation/util_test.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#189 Rename `krew remove` to `krew uninstall`
  README.md
  cmd/krew/cmd/uninstall.go
  docs/DEVELOPER_GUIDE.md
  docs/USER_GUIDE.md
  pkg/installation/install.go
  pkg/installation/install_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#191 Validate manifest file extension and kind field
  .travis.yml
  cmd/validate-krew-manifest/main.go
  cmd/validate-krew-manifest/main_test.go
  hack/check-code-patterns.sh
  pkg/constants/constants.go
  pkg/download/downloader_test.go
  pkg/environment/environment_test.go
  pkg/index/types.go
  pkg/index/validate.go
  pkg/index/validate_test.go
  pkg/installation/install_test.go
  pkg/installation/move_test.go
  pkg/testutil/tempdir.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
