Repository kubernetes-sigs/krew, pull requests merged in 2019-12, with the labels that each got.

#413 pkg/index: ignore non-.yaml files during scanning
  pkg/index/indexscanner/scanner.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#415 docs: Improvements to release doc
  docs/RELEASING_KREW.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#416 Remove license header from krew.yaml
  hack/krew.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#420 [Release]: Fix log for exe archives
  hack/make-release-artifacts.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#426 Drop sudo from travis
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#424 Remove sub go.mod from cmd
  cmd/generate-plugin-overview/generate-plugin-overview.go
  cmd/generate-plugin-overview/go.mod
  cmd/generate-plugin-overview/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#425 Run gofmt via golangci-lint
  .golangci.yml
  .travis.yml
  hack/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#427 skip/fail upgrade if no longer matches a platform
  cmd/krew/cmd/upgrade.go
  integration_test/upgrade_test.go
  internal/installation/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#428 Fix a typo in the uninstallation instruction.
  docs/USER_GUIDE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#430 Update the installation instruction to also run krew update.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#432 cmd: Friendly error messages when plugin not found
  cmd/krew/cmd/install.go
  cmd/krew/cmd/upgrade.go
  hack/run-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#433 Disallow fmt.Errorf usage through code validation
  cmd/krew/cmd/root.go
  cmd/validate-krew-manifest/main.go
  hack/verify-code-patterns.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#436 Add note to publish the plugin source code
  docs/DEVELOPER_GUIDE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#435 Improve linting and fix found issues
  .golangci.yml
  cmd/generate-plugin-overview/generate-plugin-overview.go
  cmd/validate-krew-manifest/main.go
  cmd/validate-krew-manifest/main_test.go
  internal/download/downloader.go
  internal/download/verifier.go
  internal/installation/install.go
  internal/installation/install_test.go
  internal/installation/platform.go
  internal/installation/platform_test.go
  internal/installation/upgrade.go
  internal/receiptsmigration/migration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#438 Show "Upgrading plugin %s" message
  cmd/krew/cmd/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#442 Expose `environment.NewPaths` to simplify test setup
  integration_test/uninstall_test.go
  internal/environment/environment.go
  internal/environment/environment_test.go
  internal/info/info_test.go
  internal/installation/install_test.go
  internal/receiptsmigration/migration_test.go
  internal/receiptsmigration/oldenvironment/environment.go
  internal/receiptsmigration/oldenvironment/environment_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#429 Support reading manifest url from files
  cmd/krew/cmd/install.go
  cmd/krew/cmd/install_test.go
  cmd/krew/cmd/upgrade.go
  cmd/validate-krew-manifest/main.go
  integration_test/install_test.go
  internal/index/indexscanner/scanner.go
  internal/index/indexscanner/scanner_test.go
  internal/info/info.go
  internal/installation/receipt/receipt.go
  internal/installation/receipt/receipt_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#439 Disable all first then enable needed linters
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#444 Remove mkdir redundancy
  internal/installation/move.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#449 Bump golangci-lint to v1.22.2
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
