Repository kubernetes-sigs/krew, pull requests merged in 2019-07, with the labels that each got.

#195 Save install receipt
  Gopkg.lock
  Gopkg.toml
  cmd/krew/cmd/info.go
  cmd/krew/cmd/install.go
  cmd/krew/cmd/root.go
  cmd/krew/cmd/search.go
  cmd/krew/cmd/upgrade.go
  pkg/environment/environment.go
  pkg/environment/environment_test.go
  pkg/index/indexscanner/scanner.go
  pkg/index/indexscanner/scanner_test.go
  pkg/info/info.go
  pkg/info/info_test.go
  pkg/installation/install.go
  pkg/installation/upgrade.go
  pkg/receipt/receipt.go
  pkg/receipt/receipt_test.go
  pkg/testutil/tempdir.go
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#236 Rename /test --> /integration_test
  hack/run-integration-tests.sh
  integration_test/krew_test.go
  integration_test/testutil_test.go
  test/krew/index.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#237 pkg/installation: reorder receipt save & install()
  pkg/installation/install.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#241 vendor: rename leftover vendor/ directory
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XXL

#240 integration_test: split tests into separate files
  go.mod
  integration_test/commandline_test.go
  integration_test/help_test.go
  integration_test/info_test.go
  integration_test/install_test.go
  integration_test/krew_test.go
  integration_test/list_test.go
  integration_test/search_test.go
  integration_test/testutil_test.go
  integration_test/uninstall_test.go
  integration_test/update_test.go
  integration_test/upgrade_test.go
  integration_test/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#243 Ensure that go modules are enabled in all helper scripts
  go.mod
  go.sum
  hack/run-integration-tests.sh
  hack/run-lint.sh
  hack/run-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#206 hack/run-in-docker: refactoring
  hack/run-in-docker.sh
  hack/sandboxed.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#245 Add integration tests for `krew install` with --archive and --manifest options
  integration_test/install_test.go
  integration_test/testdata/foo.tar.gz
  integration_test/testdata/foo.yaml
  integration_test/testdata/konfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#251 Fix typo in the developer docs for plugin manifest
  docs/DEVELOPER_GUIDE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#253 Make output of `krew search` easier to read
  cmd/krew/cmd/list.go
  cmd/krew/cmd/search.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#248 Use `t.Logf` instead of `glog` in tests
  hack/verify-code-patterns.sh
  integration_test/testutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#249 Add subcommand for migrating the krew home
  cmd/krew/cmd/root.go
  cmd/krew/cmd/system.go
  integration_test/system_test.go
  pkg/receiptsmigration/migration.go
  pkg/receiptsmigration/migration_test.go
  pkg/receiptsmigration/oldenvironment/environment.go
  pkg/receiptsmigration/oldenvironment/environment_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#255 hack: add script to verify receipts migration
  .travis.yml
  hack/verify-receipts-upgrade-migration.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#257 README: add github stars from shields.io
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#259 hack: add make-binary.sh for local builds
  docs/CONTRIBUTOR_GUIDE.md
  hack/make-binaries.sh
  hack/make-binary.sh
  hack/run-in-docker.sh
Labels: approved, cncf-cla: yes, kind/proposal, lgtm, size/M

#262 hack: verify builds are installable
  .travis.yml
  hack/make-release-artifacts.sh
  hack/verify-installation.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#268 hack: make run-lint.sh work with go modules
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#269 Make version field required
  cmd/validate-krew-manifest/main_test.go
  docs/DEVELOPER_GUIDE.md
  docs/USER_GUIDE.md
  pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
  pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
  pkg/index/validate.go
  pkg/index/validate_test.go
  pkg/info/info_test.go
  pkg/receipt/receipt_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#266 Unify yaml serialization dependencies
  cmd/validate-krew-manifest/main_test.go
  go.mod
  go.sum
  pkg/index/indexscanner/scanner.go
  pkg/info/info_test.go
  pkg/receipt/receipt.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#275 minor: rename environment.Path receipt path methods
  cmd/krew/cmd/root.go
  pkg/environment/environment.go
  pkg/environment/environment_test.go
  pkg/info/info.go
  pkg/info/info_test.go
  pkg/installation/install.go
  pkg/installation/upgrade.go
  pkg/receiptsmigration/migration.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#273 semver: add wrapper for SemVer functionality
  go.sum
  hack/make-release-artifacts.sh
  pkg/index/validate.go
  pkg/index/validate_test.go
  pkg/installation/semver/version.go
  pkg/installation/semver/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#276 Update plugin listings to use install receipts
  cmd/krew/cmd/list.go
  cmd/krew/cmd/search.go
  cmd/krew/cmd/upgrade.go
  pkg/installation/util.go
  pkg/receipt/receipt.go
  pkg/receipt/receipt_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#278 Refactor upgrade machinery to use semver versions
  cmd/krew/cmd/install.go
  pkg/download/verifier.go
  pkg/installation/install.go
  pkg/installation/upgrade.go
  pkg/installation/util.go
  pkg/installation/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#281 pkg/index: validate sha256 values
  cmd/validate-krew-manifest/main_test.go
  pkg/index/indexscanner/testdata/testindex/dontscan.yaml
  pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
  pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
  pkg/index/validate.go
  pkg/index/validate_test.go
  pkg/info/info_test.go
  pkg/installation/util_test.go
  pkg/receipt/receipt_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#283 pkg/testutil: add in-memory Plugin builder
  cmd/krew/cmd/install.go
  cmd/validate-krew-manifest/main.go
  cmd/validate-krew-manifest/main_test.go
  pkg/index/indexscanner/scanner.go
  pkg/index/validate_test.go
  pkg/index/validation/validate.go
  pkg/index/validation/validate_test.go
  pkg/info/info_test.go
  pkg/installation/util_test.go
  pkg/receipt/receipt_test.go
  pkg/receiptsmigration/migration.go
  pkg/testutil/plugin.go
  pkg/testutil/tempdir.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#279 Add --no-update-index option to bypass updates
  cmd/krew/cmd/install.go
  cmd/krew/cmd/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#280 pkg/receipt: move under pkg/installation
  pkg/installation/install.go
  pkg/installation/receipt/receipt.go
  pkg/installation/receipt/receipt_test.go
  pkg/installation/upgrade.go
  pkg/installation/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#285 test: remove -v from tests
  .travis.yml
  hack/run-integration-tests.sh
  hack/run-tests.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#286 Move platform detection to pkg/installation
  cmd/krew/cmd/info.go
  cmd/krew/cmd/search.go
  cmd/validate-krew-manifest/main_test.go
  hack/verify-code-patterns.sh
  pkg/index/platform_test.go
  pkg/index/validation/validate_test.go
  pkg/installation/platform.go
  pkg/installation/platform_test.go
  pkg/installation/util.go
  pkg/testutil/plugin.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#288 pkg/validation: add selector validation
  pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
  pkg/index/validation/validate.go
  pkg/index/validation/validate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#290 pkg/installation: unused pluginVersionFromPath
  pkg/installation/util.go
  pkg/installation/util_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#297 integration_test: add more test cases
  cmd/krew/cmd/install.go
  cmd/krew/cmd/list.go
  cmd/krew/cmd/system.go
  hack/verify-receipts-upgrade-migration.sh
  integration_test/help_test.go
  integration_test/install_test.go
  integration_test/list_test.go
  integration_test/testutil_test.go
  integration_test/uninstall_test.go
  integration_test/update_test.go
  integration_test/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#296 pkg/installation: cleanup refactoring
  cmd/krew/cmd/install.go
  pkg/installation/install.go
  pkg/installation/install_test.go
  pkg/installation/move.go
  pkg/installation/upgrade.go
  pkg/installation/util.go
  pkg/installation/util_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#261 Make files in `spec.platforms[]` optional
  docs/DEVELOPER_GUIDE.md
  pkg/index/indexscanner/testdata/testindex/dontscan.yaml
  pkg/index/indexscanner/testdata/testindex/plugins/bar.yaml
  pkg/index/indexscanner/testdata/testindex/plugins/foo.yaml
  pkg/index/validation/validate.go
  pkg/index/validation/validate_test.go
  pkg/installation/install.go
  pkg/installation/install_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#260 Add script to generate plugin overview page
  cmd/generate-plugin-overview/generate-plugin-overview.go
  cmd/generate-plugin-overview/go.mod
  cmd/generate-plugin-overview/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#300 Validate plugins can be removed without local manifest
  integration_test/uninstall_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
