Repository kubernetes-sigs/krew, pull requests merged in 2020-06, with the labels that each got.

#605 Include filename in manifest validator
  cmd/validate-krew-manifest/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#603 Remove receipts migration
  .github/workflows/ci.yml
  cmd/krew/cmd/root.go
  cmd/krew/cmd/system.go
  cmd/krew/main.go
  hack/verify-receipts-upgrade-migration.sh
  integration_test/system_test.go
  internal/receiptsmigration/migration.go
  internal/receiptsmigration/migration_test.go
  internal/receiptsmigration/oldenvironment/environment.go
  internal/receiptsmigration/oldenvironment/environment_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#608 Trim and minify SVG assets
  assets/logo/horizontal/black/krew-horizontal-black.svg
  assets/logo/horizontal/color/krew-horizontal-color.svg
  assets/logo/horizontal/white/krew-horizontal-white.svg
  assets/logo/icon/black/krew-icon-black.svg
  assets/logo/icon/color/krew-icon-color.svg
  assets/logo/icon/white/krew-icon-white.svg
  assets/logo/stacked/black/krew-stacked-black.svg
  assets/logo/stacked/color/krew-stacked-color.svg
  assets/logo/stacked/white/krew-stacked-white.svg
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#609 Switch to actions/setup-go@v2 to avoid PATH hack
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#612 Use go1.14 in github action
  .github/workflows/ci.yml
  go.mod
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#616 Print security notice when index is added
  cmd/krew/cmd/index.go
  cmd/krew/cmd/install.go
  cmd/krew/cmd/upgrade.go
  integration_test/index_test.go
  integration_test/install_test.go
  integration_test/upgrade_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/M
