Repository kubernetes-sigs/krew, pull requests merged in 2020-01, with the labels that each got.

#452 Bump shfmt to v3
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#455 increment plugin count in readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#450 allow linux/arm64 plugins
  cmd/validate-krew-manifest/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#453 Ensure go mod is tidied
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#458 Fix upgrade if a plugin installed from manifest
  cmd/krew/cmd/upgrade.go
  integration_test/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#465 Use ctx instead of konfig for integration test
  cmd/krew/cmd/install_test.go
  integration_test/testdata/ctx.yaml
  integration_test/testdata/konfig.yaml
  integration_test/testutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#467 Fixes typo
  docs/DEVELOPER_GUIDE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#461 Migrate to GitHub workflows
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#468 add documentation about automating release using krew-release-bot
  docs/DEVELOPER_GUIDE.md
Labels: cncf-cla: yes, size/XS

#466 Add link to sample-cli-plugin in developer guide
  docs/DEVELOPER_GUIDE.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/frozen, size/XS

#457 Show updated plugin manifests and available upgrades
  cmd/krew/cmd/update.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#464 Ensure DownloadPath is always clean
  cmd/krew/cmd/root.go
  cmd/krew/cmd/version.go
  integration_test/version_test.go
  internal/environment/environment.go
  internal/environment/environment_test.go
  internal/installation/install.go
  internal/installation/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#477 Show smaller output for updated plugins list
  cmd/krew/cmd/update.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#476 run-integration-tests.sh: pass args down
  hack/run-integration-tests.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#479 integration tests for showing new/upgradeable plugins
  integration_test/update_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#486 don't print security notice for krew itself
  cmd/krew/cmd/install.go
  cmd/krew/cmd/internal/security_notice.go
  cmd/krew/cmd/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#487 Add pull request template
  .github/pull_request_template.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
