Repository kubernetes-sigs/krew, pull requests merged in 2020-03, with the labels that each got.

#524 site: robots.txt
  site/config.yaml
  site/layouts/robots.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#525 site: add gitinfo and edit links to footer
  netlify.toml
  site/config.yaml
  site/layouts/404.html
  site/layouts/docs/section.html
  site/layouts/docs/single.html
  site/layouts/index.html
  site/layouts/partials/footer.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#527 disable travis-ci in favor of gh workflows
  .travis.yml
  cmd/krew/cmd/internal/fetch_tag_test.go
  docs/RELEASING_KREW.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#522 Move install docs to the website, add "moved" notices
  README.md
  docs/CONTRIBUTOR_GUIDE.md
  docs/DEVELOPER_GUIDE.md
  docs/KREW_ARCHITECTURE.md
  docs/NAMING_GUIDE.md
  docs/PLUGIN_LIFECYCLE.md
  docs/USER_GUIDE.md
  site/content/docs/developer-guide/distributing-with-krew.md
  site/content/docs/developer-guide/plugin-manifest.md
  site/content/docs/developer-guide/release/submitting-to-krew.md
  site/content/docs/user-guide/setup/install.md
  site/content/docs/user-guide/setup/uninstall.md
  site/content/docs/user-guide/setup/updates.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#528 docs: Add best practice on usage strings
  site/content/docs/developer-guide/develop/best-practices.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#529 site: landing page adjustments
  site/content/_index.md
  site/layouts/index.html
  site/layouts/partials/footer.html
  site/static/css/style.css
Labels: approved, cncf-cla: yes, lgtm, size/M

#531 docs: Document plugin stats dashboard
  site/content/docs/developer-guide/plugin-stats.md
  site/layouts/docs/single.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#534 site: add toc snippet for long articles
  site/content/docs/developer-guide/develop/best-practices.md
  site/content/docs/developer-guide/plugin-manifest.md
  site/layouts/shortcodes/toc.html
  site/static/css/style.css
Labels: approved, cncf-cla: yes, lgtm, size/M

#530 site: make footer show last updated
  site/layouts/partials/footer.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#526 Add receipt status
  internal/index/indexscanner/scanner.go
  internal/index/indexscanner/scanner_test.go
  internal/installation/receipt/receipt_test.go
  internal/testutil/receipt.go
  pkg/index/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#539 add popeye known homepage
  cmd/generate-plugin-overview/generate-plugin-overview.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#537 Add index list command
  cmd/krew/cmd/index.go
  internal/gitutil/git.go
  internal/index/indexoperations/index.go
  internal/index/indexoperations/index_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#540 site: Alternative layout
  site/layouts/partials/footer.html
  site/layouts/partials/header.html
  site/layouts/partials/navbar.html
  site/static/css/style.css
Labels: approved, cncf-cla: yes, lgtm, size/M

#544 site: fix url for release-automation
  site/content/docs/developer-guide/release/release-automation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#548 ListInstalledPlugins use Receipts for parsing
  internal/installation/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#547 Add custom usage template for cobra command so that usage will display 'kubectl krew' instead of just 'krew'
  .gitignore
  cmd/krew/cmd/root.go
  cmd/krew/cmd/root_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#549 add utility method to list installed plugins by index
  internal/installation/util.go
  internal/installation/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#551 test for 'kubectl' prefix in help strings
  cmd/krew/cmd/root_test.go
  integration_test/help_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#545 Add index add command
  cmd/krew/cmd/index.go
  cmd/krew/cmd/root.go
  integration_test/index_test.go
  integration_test/testutil_test.go
  internal/index/indexoperations/index.go
  internal/index/indexoperations/index_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#554 site: Add "why distribute with Krew" section
  site/content/docs/developer-guide/distributing-with-krew.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#553 remove codecov.io integration
  .dockerignore
  .github/workflows/ci.yml
  .gitignore
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#555 Populate receipt status on install/upgrade
  cmd/krew/cmd/install.go
  cmd/krew/cmd/upgrade.go
  integration_test/install_test.go
  internal/installation/install.go
  internal/installation/receipt/receipt.go
  internal/installation/receipt/receipt_test.go
  internal/installation/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#558 Refactor ListInstalledPlugins
  cmd/krew/cmd/list.go
  cmd/krew/cmd/search.go
  cmd/krew/cmd/update.go
  cmd/krew/cmd/upgrade.go
  internal/installation/util.go
  internal/installation/util_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/M

#564 site: fix slug for release-automation page
  site/content/docs/developer-guide/release/release-automation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#560 cmd: refactor `list` to work with custom indexes
  cmd/krew/cmd/list.go
  cmd/krew/cmd/list_test.go
  integration_test/list_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/M

#563 cmd/info: Support for multiple indexes
  cmd/krew/cmd/info.go
  integration_test/info_test.go
  internal/index/indexscanner/scanner.go
  internal/info/info.go
  internal/info/info_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/L

#567 remove unused type installation.PluginEntry
  internal/installation/install.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/XS

#569 test: validate krew list output is sorted alphabetically
  integration_test/list_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/M

#568 Use special "detached" index for manifest plugins
  cmd/krew/cmd/install.go
  integration_test/install_test.go
  integration_test/testutil_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/S

#572 integration_test: Use new helper method
  integration_test/install_test.go
  integration_test/testutil_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/S

#570 various naming utilities for canonicalization and display
  cmd/krew/cmd/list.go
  cmd/krew/cmd/list_test.go
  cmd/krew/cmd/namingutils.go
  cmd/krew/cmd/namingutils_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/L

#577 Fix mispelling of hack folder
  docs/CONTRIBUTOR_GUIDE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#575 integration_test: change validPlugin2
  integration_test/testutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
