Repository kubernetes-sigs/krew, pull requests merged in 2020-04, with the labels that each got.

#578 Document that gnu utils are required in mac
  docs/CONTRIBUTOR_GUIDE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#585 build untagged commits with + to indicate commit
  hack/make-release-artifacts.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#582 integration_test: Refine cmd run utilities
  integration_test/commandline_test.go
  integration_test/index_test.go
  integration_test/info_test.go
  integration_test/install_test.go
  integration_test/testutil_test.go
  integration_test/uninstall_test.go
  integration_test/update_test.go
  integration_test/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#583 Check index or plugin name safety in cmd
  cmd/krew/cmd/index.go
  cmd/krew/cmd/install.go
  cmd/krew/cmd/uninstall.go
  cmd/krew/cmd/upgrade.go
  integration_test/index_test.go
  integration_test/install_test.go
  integration_test/uninstall_test.go
  integration_test/upgrade_test.go
  internal/index/indexoperations/index.go
  internal/index/indexoperations/index_test.go
  internal/index/indexscanner/scanner.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#574 cmd: make krew search work with multiple indexes
  cmd/krew/cmd/search.go
  integration_test/search_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/L

#584 constants: change the variable name
  cmd/krew/cmd/index.go
  cmd/krew/cmd/update.go
  cmd/krew/cmd/version.go
  integration_test/index_test.go
  integration_test/testutil_test.go
  pkg/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#590 fix const references
  cmd/krew/cmd/search.go
  integration_test/index_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/P0, size/XS

#589 site: fix some links, rewording
  site/content/docs/developer-guide/release/submitting-to-krew.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#592 Remove editor-speciifc ignores in .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#591 site: bump plugin count in home
  site/content/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#588 cmd: Update each index instead of just default
  cmd/krew/cmd/install.go
  cmd/krew/cmd/search.go
  cmd/krew/cmd/system.go
  cmd/krew/cmd/update.go
  cmd/krew/cmd/upgrade.go
  integration_test/index_test.go
  integration_test/update_test.go
  internal/index/indexoperations/index.go
  internal/index/indexoperations/index_test.go
  internal/testutil/tempdir.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/L

#593 Show new/updated plugins list after index updates
  cmd/krew/cmd/update.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/M

#595 multi-index: Add default index if none exists
  cmd/krew/cmd/install.go
  cmd/krew/cmd/system.go
  cmd/krew/cmd/update.go
  cmd/krew/cmd/upgrade.go
  integration_test/index_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/M

#594 cmd: modify upgrade to work with multiple indexes
  cmd/krew/cmd/namingutils.go
  cmd/krew/cmd/namingutils_test.go
  cmd/krew/cmd/uninstall.go
  cmd/krew/cmd/upgrade.go
  integration_test/uninstall_test.go
  integration_test/upgrade_test.go
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/L
