Repository kubernetes-sigs/krew, pull requests merged in 2020-10, with the labels that each got.

#654 fix readme typo
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#656 Support arm architecture install
  site/content/docs/user-guide/setup/install.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#657 Update install.md
  site/content/docs/user-guide/setup/install.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#659 Fixed use of fish shell evaluation with (...) instead of bash style $(…)
  site/content/docs/user-guide/setup/install.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#658 Dynamic plugins list in the website
  netlify.toml
  site/config.yaml
  site/content/_index.md
  site/content/docs/user-guide/quickstart.md
  site/content/docs/user-guide/search.md
  site/content/plugins.md
  site/functions/README.md
  site/functions/go.mod
  site/functions/go.sum
  site/functions/server/main.go
  site/layouts/_default/single.html
  site/layouts/partials/footer.html
  site/layouts/partials/navbar.html
Labels: approved, cncf-cla: yes, lgtm, size/XL

#660 delete cmd/generate-plugin-overview
  cmd/generate-plugin-overview/generate-plugin-overview.go
Labels: approved, cncf-cla: yes, lgtm, size/L
