Repository kubernetes-sigs/krew, pull requests merged in 2020-12, with the labels that each got.

#669 Add documentation for default index URI variable
  site/content/docs/user-guide/configuration.md
  site/content/docs/user-guide/setup/updates.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#675 site: Document KREW_ROOT
  site/content/docs/user-guide/configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#678 Add myself to owners alias
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#679 Bump versions of most dependencies
  .github/workflows/ci.yml
  go.mod
  go.sum
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
