Repository kubernetes-sigs/krew, pull requests merged in 2020-08, with the labels that each got.

#628 Publish custom index docs
  site/content/docs/developer-guide/custom-indexes.md
  site/content/docs/user-guide/using-custom-indexes.md
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/XS

#629 fix path warning on windows
  cmd/krew/cmd/internal/setup_check.go
  cmd/krew/cmd/internal/setup_check_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#634 Some fine-tuning of krew.sigs.k8s.io
  site/content/docs/developer-guide/plugin-manifest.md
  site/content/docs/developer-guide/plugin-stats.md
  site/content/docs/user-guide/setup/uninstall.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#633 Use go 1.14 `t.Cleanup()` for simpler tests
  cmd/krew/cmd/internal/setup_check_test.go
  cmd/validate-krew-manifest/main_test.go
  integration_test/commandline_test.go
  integration_test/help_test.go
  integration_test/index_test.go
  integration_test/info_test.go
  integration_test/install_test.go
  integration_test/list_test.go
  integration_test/migration_test.go
  integration_test/search_test.go
  integration_test/testutil_test.go
  integration_test/uninstall_test.go
  integration_test/update_test.go
  integration_test/upgrade_test.go
  integration_test/version_test.go
  internal/download/downloader_test.go
  internal/environment/environment_test.go
  internal/index/indexoperations/index_test.go
  internal/index/indexscanner/scanner_test.go
  internal/indexmigration/migration_test.go
  internal/installation/install_test.go
  internal/installation/move_test.go
  internal/installation/receipt/receipt_test.go
  internal/installation/util_test.go
  internal/receiptsmigration/migration_test.go
  internal/testutil/tempdir.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#635 Update installation instructions
  site/content/docs/user-guide/setup/install.md
Labels: approved, area/multi-index, cncf-cla: yes, lgtm, size/S

#642 validate-krew-manifest: add license check
  cmd/validate-krew-manifest/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M
