Repository kubernetes-sigs/krew, pull requests merged in 2020-02, with the labels that each got.

#484 Add OS/Arch information in the krew version CLI output
  cmd/krew/cmd/version.go
  integration_test/testutil_test.go
  integration_test/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#491 Set new GOPATH env var to github actions
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#489 Check whether PATH has been set up correctly
  cmd/krew/cmd/internal/setup_check.go
  cmd/krew/cmd/internal/setup_check_test.go
  cmd/krew/cmd/root.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#493 Improve github action
  .github/workflows/ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#497 make TestKrewVersion a substring check
  integration_test/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#496 fix version stamping in build script
  hack/make-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#488 Resolve todo and add unit test
  internal/installation/util.go
  internal/installation/util_test.go
  internal/testutil/tempdir.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#494 Randomly check for krew updates
  cmd/krew/cmd/internal/fetch_tag.go
  cmd/krew/cmd/internal/fetch_tag_test.go
  cmd/krew/cmd/root.go
  docs/USER_GUIDE.md
  integration_test/testutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#499 Add krew logo assets
  assets/logo/horizontal/black/krew-horizontal-black.png
  assets/logo/horizontal/black/krew-horizontal-black.svg
  assets/logo/horizontal/color/krew-horizontal-color.png
  assets/logo/horizontal/color/krew-horizontal-color.svg
  assets/logo/horizontal/white/krew-horizontal-white.png
  assets/logo/horizontal/white/krew-horizontal-white.svg
  assets/logo/icon/black/krew-icon-black.png
  assets/logo/icon/black/krew-icon-black.svg
  assets/logo/icon/color/krew-icon-color.png
  assets/logo/icon/color/krew-icon-color.svg
  assets/logo/icon/white/krew-icon-white.png
  assets/logo/icon/white/krew-icon-white.svg
  assets/logo/stacked/black/krew-stacked-black.png
  assets/logo/stacked/black/krew-stacked-black.svg
  assets/logo/stacked/color/krew-stacked-color.png
  assets/logo/stacked/color/krew-stacked-color.svg
  assets/logo/stacked/white/krew-stacked-white.png
  assets/logo/stacked/white/krew-stacked-white.svg
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#498 Add special case for `virt` plugin
  cmd/generate-plugin-overview/generate-plugin-overview.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#500 Add logo to docs
  README.md
  assets/logo/horizontal/color/krew-horizontal-color.png
  docs/KREW_LOGO.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#503 Swap order of install and store receipt
  internal/installation/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#504 Use tagged temp dirs to simplify cleanup
  docs/RELEASING_KREW.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#505 Index migration
  cmd/krew/cmd/root.go
  cmd/krew/cmd/system.go
  internal/indexmigration/migration.go
  internal/indexmigration/migration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#506 add helper for inferring index name from input
  internal/pathutil/pathutil.go
  internal/pathutil/pathutil_test.go
  pkg/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#511 Simpler migration without external dependency
  internal/indexmigration/migration.go
  internal/indexmigration/migration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#510 Refactor existing index path functions to support multiple indexes later on
  cmd/krew/cmd/install.go
  cmd/krew/cmd/root.go
  cmd/krew/cmd/search.go
  cmd/krew/cmd/system.go
  cmd/krew/cmd/update.go
  cmd/krew/cmd/upgrade.go
  cmd/krew/cmd/version.go
  integration_test/uninstall_test.go
  integration_test/update_test.go
  internal/environment/environment.go
  internal/environment/environment_test.go
  internal/indexmigration/migration.go
  internal/info/info.go
  internal/info/info_test.go
  internal/receiptsmigration/migration.go
  pkg/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#514 Add prototype documentation site
  site/.gitignore
  site/LICENSE
  site/config.yaml
  site/content/docs/_index.md
  site/content/docs/developer-guide/_index.md
  site/content/docs/developer-guide/develop/_index.md
  site/content/docs/developer-guide/develop/best-practices.md
  site/content/docs/developer-guide/develop/naming-guide.md
  site/content/docs/developer-guide/develop/plugin-development.md
  site/content/docs/developer-guide/example-plugin-manifests.md
  site/content/docs/developer-guide/installing-locally.md
  site/content/docs/developer-guide/plugin-manifest.md
  site/content/docs/developer-guide/release/_index.md
  site/content/docs/developer-guide/release/plugin-updates.md
  site/content/docs/developer-guide/release/release-automation.md
  site/content/docs/developer-guide/release/submitting-to-krew.md
  site/content/docs/user-guide/_index.md
  site/content/docs/user-guide/install.md
  site/content/docs/user-guide/list.md
  site/content/docs/user-guide/quickstart.md
  site/content/docs/user-guide/search.md
  site/content/docs/user-guide/setup/_index.md
  site/content/docs/user-guide/setup/install.md
  site/content/docs/user-guide/setup/uninstall.md
  site/content/docs/user-guide/uninstall.md
  site/content/docs/user-guide/upgrade.md
  site/layouts/docs/single.html
  site/layouts/index.html
  site/layouts/partials/footer.html
  site/layouts/partials/header.html
  site/layouts/partials/toc.html
  site/layouts/shortcodes/output.html
  site/layouts/shortcodes/prompt.html
  site/static/css/style.css
  site/static/krew-logo.svg
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XXL

#512 Initial receipt type
  internal/index/indexscanner/scanner.go
  internal/installation/receipt/receipt.go
  internal/installation/receipt/receipt_test.go
  internal/installation/util_test.go
  internal/testutil/tempdir.go
  pkg/index/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#517 site: Advanced website navigation
  site/config.yaml
  site/content/_index.md
  site/content/docs/_index.md
  site/content/docs/developer-guide/_index.md
  site/content/docs/developer-guide/release/submitting-to-krew.md
  site/content/docs/user-guide/_index.md
  site/content/docs/user-guide/quickstart.md
  site/content/docs/user-guide/search.md
  site/layouts/404.html
  site/layouts/docs/section.html
  site/layouts/docs/single.html
  site/layouts/index.html
  site/layouts/partials/backbutton.html
  site/layouts/partials/footer.html
  site/layouts/partials/header.html
  site/layouts/partials/navbar.html
  site/static/css/style.css
  site/static/img/krew-logo.svg
  site/static/krew-logo.svg
Labels: approved, cncf-cla: yes, lgtm, size/L

#520 site: Add netlify.toml
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/S

#518 Consider HTTP status for more meaningful errors
  cmd/krew/cmd/internal/fetch_tag.go
  cmd/krew/cmd/internal/fetch_tag_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#513 Use static URL to download assets from latest release
  README.md
  docs/RELEASING_KREW.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#523 docs: Explain krew logo
  docs/KREW_LOGO.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
