Repository kubernetes-sigs/krew, pull requests merged in 2021-03, with the labels that each got.

#695 Add creation timestamp to receipts on install
  integration_test/install_test.go
  integration_test/testutil_test.go
  integration_test/upgrade_test.go
  internal/installation/install.go
  internal/installation/receipt/receipt.go
  internal/installation/receipt/receipt_test.go
  internal/installation/upgrade.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#694 hack: use go1.16 'go install pkg@ver' mode
  hack/.gitignore
  hack/install-gox.sh
  hack/make-release-notes.sh
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#698 hack: drop impi in favor of golangci-lint
  .golangci.yml
  hack/run-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#701 Docs follow up
  site/content/docs/developer-guide/custom-indexes.md
  site/content/docs/developer-guide/develop/best-practices.md
  site/content/docs/developer-guide/develop/naming-guide.md
  site/content/docs/developer-guide/develop/plugin-development.md
  site/content/docs/developer-guide/installing-locally.md
  site/content/docs/developer-guide/plugin-manifest.md
  site/content/docs/developer-guide/plugin-stats.md
  site/content/docs/developer-guide/release/plugin-updates.md
  site/content/docs/developer-guide/release/release-automation.md
  site/content/docs/user-guide/using-custom-indexes.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#703 Fixed ListIndexes treating file as index candidates
  internal/index/indexoperations/index.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#702 ISSUE-696: Explore use of t.TempDir()
  internal/testutil/tempdir.go
Labels: approved, cncf-cla: yes, lgtm, size/S
