Repository kubernetes-sigs/krew, pull requests merged in 2021-02, with the labels that each got.

#687 Docs update - user guide
  site/content/docs/user-guide/configuration.md
  site/content/docs/user-guide/install.md
  site/content/docs/user-guide/list.md
  site/content/docs/user-guide/quickstart.md
  site/content/docs/user-guide/search.md
  site/content/docs/user-guide/setup/install.md
  site/content/docs/user-guide/setup/uninstall.md
  site/content/docs/user-guide/setup/updates.md
  site/content/docs/user-guide/upgrade.md
  site/content/docs/user-guide/using-custom-indexes.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#689 Support linux/arm64 release
  hack/krew.yaml
  hack/make-binaries.sh
  site/content/docs/user-guide/setup/install.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#690 Docs update - developer guide
  site/content/docs/developer-guide/custom-indexes.md
  site/content/docs/developer-guide/develop/best-practices.md
  site/content/docs/developer-guide/develop/naming-guide.md
  site/content/docs/developer-guide/develop/plugin-development.md
  site/content/docs/developer-guide/distributing-with-krew.md
  site/content/docs/developer-guide/example-plugin-manifests.md
  site/content/docs/developer-guide/installing-locally.md
  site/content/docs/developer-guide/plugin-manifest.md
  site/content/docs/developer-guide/plugin-stats.md
  site/content/docs/developer-guide/release/plugin-updates.md
  site/content/docs/developer-guide/release/release-automation.md
  site/content/docs/developer-guide/release/submitting-to-krew.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#692 Support LICENSES filename in manifest validation
  cmd/validate-krew-manifest/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#693 add support for darwin/arm64 (Apple Silicon)
  .github/workflows/ci.yml
  cmd/validate-krew-manifest/main.go
  docs/RELEASING_KREW.md
  go.mod
  go.sum
  hack/krew.yaml
  hack/make-binaries.sh
  site/content/docs/user-guide/setup/install.md
Labels: approved, cncf-cla: yes, lgtm, size/M
