Repository kubernetes-sigs/krew, pull requests merged in 2022-06, with the labels that each got.

#784 Update the installation URL of golangci-lint
  hack/run-lint.sh
Labels: size/XS, lgtm, cncf-cla: yes, approved

#781 Replace an unmaintained action
  .github/workflows/ci.yml
Labels: size/S, lgtm, cncf-cla: yes, approved

#786 Improved a installation script for fish
  site/content/docs/user-guide/setup/install.md
Labels: size/XS, cncf-cla: yes
